#bin_PROGRAMS=secureappsrc
#secureappsrc_SOURCES = secureappsrc.c crypto.c
#secureappsrc_CFLAGS = $(GST_CFLAGS)
#secureappsrc_LDFLAGS = $(GST_LIBS) $(GST_PLUGIN_LDFLAGS) -lion -ldl
#secureappsrc_LIBTOOLFLAGS = --tag=disable-static

noinst_HEADERS = \
  crypto.h

#bin_PROGRAMS=secure-gst-codec2
#secure_gst_codec2_SOURCES = secure-gst-codec2.c crypto.c
#secure_gst_codec2_LDFLAGS = -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0 -lion -ldl
#secure_gst_codec2_LIBTOOLFLAGS = --tag=disable-static

bin_PROGRAMS=secureappsrc2
secureappsrc2_SOURCES = secureappsrc2.c crypto.c
secureappsrc2_CFLAGS = $(GST_CFLAGS)
secureappsrc2_LDFLAGS = $(GST_LIBS) $(GST_PLUGIN_LDFLAGS) -lion -ldl
secureappsrc2_LIBTOOLFLAGS = --tag=disable-static
