option('usedmaheap', type : 'boolean', value : 'false', description: 'Use DMA buffer heap.')
option('contiguous_mem_option', type : 'combo',
    choices : ['op0', 'op1'], value : 'op0',
    description : 'The contiguous memory options, like different heap name')
option('disable_secure_copy', type : 'boolean', value : 'false',
    description: 'Disable secure copy since it is not supported')
option('ASAN', type: 'boolean', value: false, description: 'Enable address sanitizers tool')
option('drm-optimization', type : 'boolean', value : false, description: 'Use non-contiguous memory by default if DRM optimization enabled')
